version: '3.7'

services:
  postgres:
    container_name: tourplanner
    image: postgres:15
    environment:
      POSTGRES_USER: josip
      POSTGRES_PASSWORD: josip
      POSTGRES_DB: tours
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
